src/Entity/Hopital.php
<?php

namespace App\Entity;

use App\Repository\HopitalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HopitalRepository::class)]
class Hopital
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Localisation = null;

    #[ORM\OneToMany(targetEntity: HopitalImage::class, mappedBy: 'Hopital')]
    private Collection $hopitalImages;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column]
    private ?int $Num = null;

    public function __construct()
    {
        $this->hopitalImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(string $Localisation): static
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    /**
     * @return Collection<int, HopitalImage>
     */
    public function getHopitalImages(): Collection
    {
        return $this->hopitalImages;
    }

    public function addHopitalImage(HopitalImage $hopitalImage): static
    {
        if (!$this->hopitalImages->contains($hopitalImage)) {
            $this->hopitalImages->add($hopitalImage);
            $hopitalImage->setHopital($this);
        }

        return $this;
    }

    public function removeHopitalImage(HopitalImage $hopitalImage): static
    {
        if ($this->hopitalImages->removeElement($hopitalImage)) {
            // set the owning side to null (unless already changed)
            if ($hopitalImage->getHopital() === $this) {
                $hopitalImage->setHopital(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getNum(): ?int
    {
        return $this->Num;
    }

    public function setNum(int $Num): static
    {
        $this->Num = $Num;

        return $this;
    }
}

src/Entity/Medecin.php
<?php

namespace App\Entity;

use App\Repository\MedecinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MedecinRepository::class)]
class Medecin
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $specialite = null;

    #[ORM\Column(length: 20)]
    private ?string $email = null;

    #[ORM\OneToMany(targetEntity: Offre::class, mappedBy: 'Medecin')]
    private Collection $offres;

    #[ORM\OneToMany(targetEntity: Consultation::class, mappedBy: 'medecin')]
    private Collection $consultations;

    public function __construct()
    {
        $this->offres = new ArrayCollection();
        $this->consultations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): static
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Offre>
     */
    public function getOffres(): Collection
    {
        return $this->offres;
    }

    public function addOffre(Offre $offre): static
    {
        if (!$this->offres->contains($offre)) {
            $this->offres->add($offre);
            $offre->setMedecin($this);
        }

        return $this;
    }

    public function removeOffre(Offre $offre): static
    {
        if ($this->offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getMedecin() === $this) {
                $offre->setMedecin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Consultation>
     */
    public function getConsultations(): Collection
    {
        return $this->consultations;
    }

    public function addConsultation(Consultation $consultation): static
    {
        if (!$this->consultations->contains($consultation)) {
            $this->consultations->add($consultation);
            $consultation->setMedecin($this);
        }

        return $this;
    }

    public function removeConsultation(Consultation $consultation): static
    {
        if ($this->consultations->removeElement($consultation)) {
            // set the owning side to null (unless already changed)
            if ($consultation->getMedecin() === $this) {
                $consultation->setMedecin(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?User $User_Reservation = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Urgence $Urgence = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserReservation(): ?User
    {
        return $this->User_Reservation;
    }

    public function setUserReservation(?User $User_Reservation): static
    {
        $this->User_Reservation = $User_Reservation;

        return $this;
    }

    public function getUrgence(): ?Urgence
    {
        return $this->Urgence;
    }

    public function setUrgence(?Urgence $Urgence): static
    {
        $this->Urgence = $Urgence;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): static
    {
        $this->Date = $Date;

        return $this ;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Entity/Urgence.php
<?php

namespace App\Entity;

use App\Repository\UrgenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UrgenceRepository::class)]
class Urgence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $NombreLit = null;

    #[ORM\Column(length: 255)]
    private ?string $Specialite = null;

    #[ORM\Column]
    private ?int $NombreLitDisponible = null;

    #[ORM\OneToOne(cascade: ['persist'])]
    private ?Hopital $Hopital = null;

    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'Urgence')]
    private Collection $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNombreLit(): ?int
    {
        return $this->NombreLit;
    }

    public function setNombreLit(int $NombreLit): static
    {
        $this->NombreLit = $NombreLit;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->Specialite;
    }

    public function setSpecialite(string $Specialite): static
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    public function getNombreLitDisponible(): ?int
    {
        return $this->NombreLitDisponible;
    }

    public function setNombreLitDisponible(int $NombreLitDisponible): static
    {
        $this->NombreLitDisponible = $NombreLitDisponible;

        return $this;
    }

    public function getHopital(): ?Hopital
    {
        return $this->Hopital;
    }

    public function setHopital(?Hopital $Hopital): static
    {
        $this->Hopital = $Hopital;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setUrgence($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUrgence() === $this) {
                $reservation->setUrgence(null);
            }
        }

        return $this;
    }
}

src/Form/MedecinType.php
<?php

namespace App\Form;

use App\Entity\Medecin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType; // Corrected import
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class MedecinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'constraints' => [
                    new NotBlank(['message' => 'Le nom est obligatoire']), // Corrected syntax
                ],
                'attr' => [
                    'class' => 'search-form input',
                ]
            ])
            ->add('prenom', TextType::class, [
                'constraints' => [
                    new NotBlank(['message' => 'Le prénom est obligatoire']), // Corrected syntax
                ],
                'attr' => [
                    'class' => 'search-form input',
                ]
            ])
            ->add('specialite', ChoiceType::class, [
                'choices' => [
                    'Généraliste' => 'Généraliste',
                    'Dentiste' => 'Dentiste',
                    'Cardiologue' => 'Cardiologue',
                    "Pédiatrie" => "Pédiatrie",
                    "Gynécologie" => "Gynécologie",
                    "Neurologie" => "Neurologie",
                    "Dermatologie" => "Dermatologie",
                ],
                'attr' => [
                    'class' => 'search-form input',
                ]
            ])
            ->add('email', EmailType::class, [
                'constraints' => [
                    new NotBlank(message:"L'Email est obligatoire"),
                    new Email(['message' => 'Email is not valid.']) // Corrected syntax
                ],
                'attr' => [
                    'class' => 'search-form input',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Medecin::class,
        ]);
    }
}

src/Controller/MedecinController.php
<?php

namespace App\Controller;

use App\Entity\Medecin;
use App\Form\MedecinType;
use App\Repository\MedecinRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Endroid\QrCode\Color\Color;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelLow;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Label\Label;
use Endroid\QrCode\Logo\Logo;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\Label\Font\NotoSans;



#[Route('/medecin')]
class MedecinController extends AbstractController
{
    #[Route('/', name: 'app_medecin_index', methods: ['GET'])]
    public function index(MedecinRepository $medecinRepository): Response
    {
        return $this->render('medecin/index.html.twig', [
            'medecins' => $medecinRepository->findAll(),
        ]);
    }

    #[Route('/list', name: 'app_medecin_list', methods: ['GET'])]
    public function list(MedecinRepository $medecinRepository): Response
    {
        $medecins = $medecinRepository->findAll();
        
        $writer = new PngWriter(); // Instantiate the PngWriter class
        
        foreach ($medecins as $medecin) {
            $content = sprintf(
                "ID: %d, Nom: %s, Prénom: %s, Spécialité: %s, Email: %s",
                $medecin->getId(),
                $medecin->getNom(),
                $medecin->getPrenom(),
                $medecin->getSpecialite(),
                $medecin->getEmail()
            );
            
            $qrCode = QrCode::create($content)
                ->setEncoding(new Encoding('UTF-8'))
                ->setSize(120)
                ->setMargin(0)
                ->setForegroundColor(new Color(0, 0, 0))
                ->setBackgroundColor(new Color(255, 255, 255));
            
            $medecin->qrCode = $writer->write($qrCode)->getDataUri();
        }
        
        return $this->render('medecin/frontindex.html.twig', [
            'medecins' => $medecins,
        ]);
    }

    #[Route('/new', name: 'app_medecin_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $medecin = new Medecin();
        $form = $this->createForm(MedecinType::class, $medecin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($medecin);
            $entityManager->flush();

            return $this->redirectToRoute('app_medecin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('medecin/new.html.twig', [
            'medecin' => $medecin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_medecin_show', methods: ['GET'])]
    public function show(Medecin $medecin): Response
    {
        return $this->render('medecin/show.html.twig', [
            'medecin' => $medecin,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_medecin_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Medecin $medecin, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MedecinType::class, $medecin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_medecin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('medecin/edit.html.twig', [
            'medecin' => $medecin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_medecin_delete', methods: ['POST'])]
    public function delete(Request $request, Medecin $medecin, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medecin->getId(), $request->request->get('_token'))) {
            $entityManager->remove($medecin);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_medecin_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/medecin/_delete_form.html.twig
<form method="post" action="{{ path('app_medecin_delete', {'id': medecin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medecin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/medecin/_form.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire dans un tableau vertical</title>
    <style>
        /* Style pour le tableau */
        .styled-table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 10px;
            overflow: hidden;
            border: 1px solid #007bff; /* Contour de tableau bleu */
        }
        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        .styled-table th {
            background-color: #007bff;
            color: white;
        }
        .styled-table tr:last-child td {
            border-bottom: none;
        }
        /* Style pour le formulaire */
        .styled-form {
            width: 100%;
            max-width: 400px;
            margin: 20px auto;
            padding: 20px;
            border: 1px solid #007bff; /* Contour de formulaire bleu */
            border-radius: 10px;
            background-color: #f9f9f9;
        }
        .styled-form .form-group {
            margin-bottom: 20px;
        }
        .styled-form label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .styled-form input[type="text"],
        .styled-form input[type="email"],
        .styled-form select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .styled-form button {
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .map-icon {
            background-image: url('https://maps.gstatic.com/tactile/pane/default_geocode-1x.png');
            width: 24px;
            height: 24px;
            background-size: cover;
            display: inline-block;
        }
    </style>
</head>
<body>

<table class="styled-table">
    <tr>
        <th colspan="2">Informations</th>
    </tr>
    <tr>
        <td>
            {{ form_start(form,{'attr' : {'class' : 'styled-form','novalidate' : 'novalidate' }}) }}
                <div class="form-group">
                    {{form_label(form.nom,'Nom :')}}
                    {{form_widget(form.nom)}}
                    {{form_errors(form.nom)}}
                </div>
                <div class="form-group">
                    {{form_label(form.prenom,'Prénom :')}}
                    {{form_widget(form.prenom)}}
                    {{form_errors(form.prenom)}}
                </div>
                <div class="form-group">
                    {{form_label(form.specialite,'Specialité :')}}
                    {{form_widget(form.specialite)}}
                    {{form_errors(form.specialite)}}
                </div>
                <div class="form-group">
                    {{form_label(form.email,'Email :')}}
                    {{form_widget(form.email)}}
                    {{form_errors(form.email)}}
                </div>
                <button type="submit">Enregistrer</button>
            {{ form_end(form) }}
        </td>
        <td class="map-icon"></td> <!-- Icône de la carte -->
    </tr>
</table>

</body>
</html>

templates/medecin/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit Medecin{% endblock %}

{% block body %}
    <h1>Edit Medecin</h1>

    {{ include('medecin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_medecin_index') }}">back to list</a>

    {{ include('medecin/_delete_form.html.twig') }}
{% endblock %}

templates/medecin/frontindex.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panacea | Medecins{% endblock %}

{% block nav %}
<div class="main-menu">
    <nav class="navigation">
        <ul class="nav menu">
            <li><a href="index.html">Accueil</a></li>
            <li class="active"><a href="{{ path('app_medecin_list') }}">Médecins</a></li>
            <li><a href="#">Hôpitaux</a></li>
            <li><a href="#">Laboratoires</a></li>
            <li><a href="#">Pharmacies</a></li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block body %}
<section class="ordonnance-table section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Nos Docteurs</h2>
                    <img src="{{ asset('front/img/about-img.jpg') }}" alt="#">
                    <p>Votre bien-être est notre priorité, voici nos docteurs.</p>
                    <a class="btn btn-primary" style="font-size: 16px;" href="{{ path('app_consultation_list',{'id' : 1}) }}">Mes consultations</a>
                </div>
            </div>
        </div>
        <div class="row">
            {% for med in medecins %}
            <!-- Ordonnance Unique -->
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="ordonnance-card" style="border: 2px solid #5DADE2;margin-bottom: 20px;">
                   <!-- En-tête de l'ordonnance -->
                    <div class="card-header" style="background-color: #5DADE2; color: white; text-align: center;">
                        <h4 class="title">Docteur N°{{ med.id }}</h4>
                    </div>
                    <img src="{{ med.qrCode }}" alt="QR Code">

                    <!-- Détails de l'ordonnance -->
                    <div class="card-body">
                        <p class="attribute-label" style="font-size: 18px;"><strong>Nom et prénom :</strong></p>
                        <p class="attribute-value" style="font-size: 16px;">{{ med.prenom }} {{ med.nom }}</p>
                        <p class="attribute-label" style="font-size: 18px;"><strong>Spécialité :</strong></p>
                        <p class="attribute-value" style="font-size: 16px;">{{ med.specialite }}</p>
                        <p class="attribute-label" style="font-size: 18px;"><strong>Email :</strong></p>
                        <p class="attribute-value" style="font-size: 16px;">{{ med.email }}</p>
                        <p class="attribute-label" style="font-size: 18px;"><strong>Consultation :</strong></p>
                        <a class="btn btn-primary" style="font-size: 16px;" href="{{ path('app_consultation_new',{'id' : med.id}) }}">Prenez rendez-vous</a>
                    </div>
                </div>
            </div>
            <!-- Fin Ordonnance Unique -->
            {% endfor %}
        </div>
    </div>
</section>
<!-- Fin Table des ordonnances -->

{% endblock %}

templates/medecin/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Medecin index{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        /* Style pour le tableau */
        .styled-table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 10px;
            overflow: hidden;
            border: 2px solid #007bff; /* Contour de tableau bleu */
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); /* Ombre douce */
        }
        .styled-table th,
        .styled-table td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #f0f0f0; /* Ligne séparatrice */
        }
        .styled-table th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
        }
        .styled-table tr:last-child td {
            border-bottom: none;
        }
        .styled-table tbody tr:hover {
            background-color: #f8f8f8; /* Couleur de survol */
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Medecin index</h1>

    <table class="styled-table table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Spécialité</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for medecin in medecins %}
            <tr>
                <td>{{ medecin.id }}</td>
                <td>{{ medecin.nom }}</td>
                <td>{{ medecin.prenom }}</td>
                <td>{{ medecin.specialite }}</td>
                <td>{{ medecin.email }}</td>
                <td>
                    <a href="{{ path('app_medecin_show', {'id': medecin.id}) }}" class="btn btn-info btn-sm">Voir</a>
                    <a href="{{ path('app_medecin_edit', {'id': medecin.id}) }}" class="btn btn-primary btn-sm">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_medecin_new') }}" class="btn btn-success">Créer un nouveau</a>
{% endblock %}

templates/medecin/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Medecin{% endblock %}

{% block body %}
    <h1>Create new Medecin</h1>

    {{ include('medecin/_form.html.twig') }}

    <a href="{{ path('app_medecin_index') }}">back to list</a>
{% endblock %}

templates/medecin/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Medecin{% endblock %}

{% block body %}
    <h1>Medecin</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ medecin.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ medecin.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ medecin.prenom }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ medecin.specialite }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ medecin.email }}</td>
            </tr>
        </tbody>
    </table>

    <h1>Consultations</h1>
    <table class="table">
        <tbody>
        {% if medecin.consultations is not empty %}
            {% for cons in medecin.consultations %}
            <tr>
                <th>Consultation</th>
                <td>{{ cons.id }}</td>
            </tr>
            <tr>
                <th>Client</th>
                <td>{{ cons.Client.prenom }} {{ cons.Client.nom }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ cons.date | date('Y-m-d H:i:s')}}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ cons.prix }}</td>
            </tr>
            {% endfor %}
        {% endif %}
            
        </tbody>
    </table>



    <a href="{{ path('app_medecin_index') }}">back to list</a>

    <a href="{{ path('app_medecin_edit', {'id': medecin.id}) }}">edit</a>

    {{ include('medecin/_delete_form.html.twig') }}
{% endblock %}